### ISSUE TITLE
Code Snippets are not displayed in gist overview

### ISSUE THREAD

**Issue by K-lemens** [lauthieb/code-notes#110] opened 2019-11-04 14:16 UTC
After downloading and updating to the newest version of Code Notes (v. 1.2.3) my Snippets stored in Gist are not displayed correctly. The titel of each Note is shown, but the Note is displayed empty. Though when I click on "Edit Notes" the full text, which I also can see in my Gist online, is displayed and can be edited.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50579621/68127142-8d357e00-ff15-11e9-9e2f-467438c960e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chorme 77.0.3865.120
 - Version: 10.0.18356 Build 18356

**Comment by lauthieb** [comment] 2019-11-04 14:57
Thanks a lot @K-lemens for reporting this.
We will investigate as soon as possible.
Can you download the 1.2.2 please : https://github.com/lauthieb/code-notes/releases/tag/1.2.2
You can find the .dmg/exe/AppImage files in assets of this release note.
Thanks a lot.

**Comment by lauthieb** [comment] 2019-11-04 14:58
@jack-chapman do you think that this bug could be caused by https://github.com/lauthieb/code-notes/commit/8b530087937596c510cf68f0243c0677e2f222df ?

**Comment by lauthieb** [comment] 2019-11-04 14:59
@kodaman2 @flashadvocate, may I have your help too please?

**Comment by flashadvocate** [comment] 2019-11-04 15:56
I can confirm this bug as of the #95 PR. I did notice that switching contexts sometimes made it work. It affected some snippets but not others.

**Comment by kodaman2** [comment] 2019-11-05 00:43
Will definitely need some good debugging can't make any promises this week.
Maybe until the weekend I'll take a look.

Probably a good idea to add some integration unit testing to catch this UI
rendering issues too.

**Comment by lauthieb** [comment] 2019-11-06 11:56
No problem @kodaman2.
Yes, I think Cypress could do the job but it's not prioritized for the moment.

**Comment by K-lemens** [comment] 2019-11-07 08:05
Wanted to let you know that in v1.2.2 it worked without a flaw.

**Comment by S0U1SB4N3** [comment] 2019-11-07 17:07
confirmed 1.2.3 issue 
<img width="1160" alt="Screen Shot 2019-11-07 at 12 05 14 PM" src="https://user-images.githubusercontent.com/22788570/68410675-1e476780-0157-11ea-9d19-bb2a04e0f760.png">
this is on mac latest OS updated

**Comment by kodaman2** [comment] 2019-11-08 02:00
I suppose PR #74 has nothing to do with this? Is on the same release. It was also merged to master before #95. Just throwing that out there. 🙂

**Comment by kodaman2** [comment] 2019-11-08 11:34
I am not entirely sure how to debug this issue, I see the problem on code-notes-v1.2.3.dmg for sure, though when I run the master or PR #95 commit with `npm run dev` I cannot reproduce the error.

@flashadvocate 
- can you provide some context how you were able to reproduce issue with PR #95? 
- Which npm script did you run, or did you build the install again?

**Comment by kodaman2** [comment] 2019-11-08 12:00
I got a quick test done PR #95 is not the problem, here what I did to test it.

Pull code from commit 5991e90833136a28852dab21b6572ec99b55aa57 which was before PR #74, then manually added the code changes from PR #95, I then proceeded to:

- npm install
- npm run build
- installed on my mac mojave (don't think OS matters for this bug though)

Works perfectly fine. pinging @marvpaul for his input. I still don't understand how I can't reproduce the bug with `npm run dev` on master branch.

@lauthieb I think for the future it would be good to run builds for each PR to make sure nothing breaks.

**Comment by marvpaul** [comment] 2019-11-08 14:21
Also the bug appears for local snippets as well.

**Comment by kodaman2** [comment] 2019-11-08 19:24
> @kodaman2 thanks for pinging me.
> 
> I started a debug session for the production app and figured out that this error seems to be the problem
> <img alt="Bildschirmfoto 2019-11-08 um 15 26 00" width="1680" src="https://user-images.githubusercontent.com/10696948/68483612-2cbb7f00-023c-11ea-8353-5ba8cfd50a0c.png">
> Not sure if it helps.
> 
> What else I have done:
> 
> * local rebuild of current master --> Bug is still there, also with local snippets!
> * local build of commit # [3f43a9a](https://github.com/lauthieb/code-notes/commit/3f43a9ae64a716ac3c1cfad7845fb73b79614a37) , which includes my changes from PR #74 --> Bug does not appear
> * local build of commit # [fd28232](https://github.com/lauthieb/code-notes/commit/fd282321593140a3895f10d2e0ec8546503aa124) --> Bug does not appear
> * local build of commit # [29d3a74](https://github.com/lauthieb/code-notes/commit/29d3a74485d4baac43744a4c7fd93fb53881a442) --> Bug does not appear
> * local build of commit # [1340843](https://github.com/lauthieb/code-notes/commit/13408439c6e13bc7677bd65d419eb2e6533222ee) --> Bug appears
> 
> So hopefully I can say the reason for that bug lays in a commit somewhere between [29d3a74](https://github.com/lauthieb/code-notes/commit/29d3a74485d4baac43744a4c7fd93fb53881a442) and [1340843](https://github.com/lauthieb/code-notes/commit/13408439c6e13bc7677bd65d419eb2e6533222ee)
> 
> My guess is that this commit causes the problem: [8b53008](https://github.com/lauthieb/code-notes/commit/8b530087937596c510cf68f0243c0677e2f222df)
> 
> I'm out for now. Perhaps someone else will have some time to further investigate the reason for this problem and hopefully can confirm what I've found out so far.

That is a very good assessment @marvpaul , if this was my repo, I would revert back to that commit which broke the app, then manually add the following code commits after that without any major changes once is all tested and built then I would work on major vue changes and stuff like that. I think the process was a bit loose along the ways. Just my 2c lol don't take it personal.

**Comment by kodaman2** [comment] 2019-11-09 02:10
I'm not an expert on electron apps but shouldn't this bug be visible during `npm run dev`? If not, then why is dev different than build? My point is that the app run fine on latest master on dev, why is that?

**Comment by marvpaul** [comment] 2019-11-09 08:55
I had some time today to further analyze the source of this bug. 
The problem should be 8b530087937596c510cf68f0243c0677e2f222df 
I've done: 
- local build of 8b530087937596c510cf68f0243c0677e2f222df --> bug appears
- local build of 29d3a74485d4baac43744a4c7fd93fb53881a442 --> Bug does not appear

@jack-chapman do you have an idea what could be the problem?

At first I though it could be a problem with the updated Electron version (perhaps a bug?), but I tried to do a build with electron v. 1.8.8 on commit 8b530087937596c510cf68f0243c0677e2f222df and the bug still appears.

**Comment by kodaman2** [comment] 2019-11-09 22:22
Good luck finding this bug gents, tons of npm packages were upgraded. I would highly recommend re-doing #93 in very short commits, as of now #93 has only 4 commits with the first one has really all the changes already. So is very difficult to point to which a specific package, code change broke the app. 

I think the issue is related to the vue templates edits + package upgrades, I tried to step trace back the changes, but I think it would be far easier to just remove it all together from the baseline, and create a dev branch to do this vue upgrade more carefully of course with build tests as the upgrade progresses.

**Comment by lauthieb** [comment] 2019-11-11 09:38
Hi @kodaman2, thanks a lot for your investigation. Feel free to begin a new branch and try to resolve this bug. I can’t do this for the moment, my work takes me too much time unfortunately :( but I’ll try to answer you ASAP if you have any question on this subject. Many thanks another time.

**Comment by kodaman2** [comment] 2019-11-11 18:08
No worries mine too, I'll try to work on it here and there on my evenings
and weekends. I was just planning for now to subtract the commit 8b533008
from master and submit a PR so master is restored to fully functional
again. After that I could try to redo that 8b533008 commit on another
branch but with smaller commits to try and find the package causing the
issue.

**Comment by lauthieb** [comment] 2019-11-25 22:37
Hi @kodaman2, did you work on this or no?
I've updated our website to reference the 1.2.2 in the download's section for the moment.

**Comment by kodaman2** [comment] 2019-11-26 13:01
@lauthieb
I've tried a few times with no luck, you downgrade one package and the
whole thing crumbles. As much as I hate to say it, I think the easiest
thing to do is to reset to a working commit, then ping each individual PR
that was merged after that.

Going forward I'd be a bit more careful about merging commits without doing
a production build and dev test.

**Comment by lauthieb** [comment] 2019-12-03 23:49
Thanks to a great PR of @kodaman2, this issue is now fixed.
You can download the "new" 1.2.3 version there: https://github.com/lauthieb/code-notes/releases/tag/1.2.3
Thanks everyone for this amazing work. You're awesome <3

**Closed by lauthieb** 2019-12-03 23:49 UTC
Labels: bug 🐛
