### ISSUE TITLE
Editing Gist duplicates instead of editing - Deleting Snippit seems to Crash and reloads.

### ISSUE THREAD

**Issue by ImNotLiam** [lauthieb/code-notes#37] opened 2018-02-20 15:15 UTC
### Expected Behavior
Editing gist should of edited the original and not create a copy of it.

### Current Behavior
Below is a screenshot of what happens when you currently edit one.
![image](https://user-images.githubusercontent.com/13552261/36431862-9964c8ac-1650-11e8-8c88-5372e95fbe75.png)

### Steps to Reproduce (for bugs)
1. Edit the language for any gist
2. click update

### Your Environment
* 1.2.0
* Windows 10

**Comment by lauthieb** [comment] 2018-02-20 22:52
Hello @ImNotLiam, when I edit a language of a file in a gist, there's no problem for me...

**Comment by lauthieb** [comment] 2018-02-26 09:53
?? @ImNotLiam

**Comment by ImNotLiam** [comment] 2018-02-26 13:30
For me it seems to duplicate the gist. Not sure if it is supposed to do this or overwrite the old one.

**Comment by lauthieb** [comment] 2018-10-29 19:54
I can't reproduce on v1.2.0 and MacOS sorry. I close it, feel free to reopen with more examples.
Thanks @ImNotLiam :)

**Closed by lauthieb** 2018-10-29 19:54 UTC
Labels: bug
